[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags =
    -DOINK_FEATURE_GNSS=1
    -DOINK_GNSS_BAUD=9600
    -DOINK_GNSS_UART_RX=D6
    -DOINK_GNSS_UART_TX=D7
    -DOINK_GNSS_HW_SERIAL_NUM=1

lib_deps = 
    olikraus/U8g2@^2.35.19
    h2zero/NimBLE-Arduino@1.4.2
    ESP32Async/AsyncTCP@^3.3.2
    ESP32Async/ESPAsyncWebServer@^3.6.0
    bblanchon/ArduinoJson@^7.0.4
    greiman/SdFat@^2.2.3
    mikalhart/TinyGPSPlus@^1.0.3
